from sqlalchemy import create_engine, Column, Integer, String, Float, Boolean, DateTime, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./data/ev_stations.db")

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Station(Base):
    __tablename__ = "stations"

    id = Column(Integer, primary_key=True, index=True)
    nrel_id = Column(Integer, unique=True, index=True)
    station_name = Column(String)
    street = Column(String)
    city = Column(String)
    state = Column(String)
    zip_code = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    status_code = Column(String)        # E=open, P=planned, T=temporarily closed
    ev_level1_ports = Column(Integer, default=0)
    ev_level2_ports = Column(Integer, default=0)
    ev_dc_fast_ports = Column(Integer, default=0)
    ev_network = Column(String)
    owner_type = Column(String)
    open_date = Column(String)
    last_synced = Column(DateTime, default=datetime.utcnow)


class StationSnapshot(Base):
    """One row per polling cycle per station — builds the time series."""
    __tablename__ = "station_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    nrel_id = Column(Integer, index=True)
    status_code = Column(String)
    polled_at = Column(DateTime, default=datetime.utcnow, index=True)


class StationHealth(Base):
    """Computed health metrics per station, updated each cycle."""
    __tablename__ = "station_health"

    id = Column(Integer, primary_key=True, index=True)
    nrel_id = Column(Integer, unique=True, index=True)
    uptime_rate = Column(Float)
    outage_count = Column(Integer, default=0)
    mtbf_hours = Column(Float)
    availability_score = Column(Float)
    last_computed = Column(DateTime, default=datetime.utcnow)


class AnomalyAlert(Base):
    """Alerts generated by the anomaly detection engine."""
    __tablename__ = "anomaly_alerts"

    id = Column(Integer, primary_key=True, index=True)
    nrel_id = Column(Integer, index=True)
    alert_type = Column(String)         # zscore | iqr | rolling
    severity = Column(String)           # low | medium | high
    message = Column(Text)
    detected_at = Column(DateTime, default=datetime.utcnow)
    resolved = Column(Boolean, default=False)


def init_db():
    Base.metadata.create_all(bind=engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
